Add support for SpaceAutomation
GitTools/GitVersion pull request #2545
Opened 2021-01-15 00:14 UTC by matkoch

Let me know if anything is missing to support a new CI system.

2021-01-15 00:16 UTC, asbjornu commented
Thanks. Some tests would be nice.

2021-01-15 01:28 UTC, matkoch commented
Not exactly sure what you wanna test here. Do you want to add a sample CI?

2021-01-15 06:14 UTC, arturcic commented
@matkoch have a look here https://github.com/GitTools/GitVersion/blob/1f8ff17dbab759b20ee361e7a6fc0488c985a803/src/GitVersionExe.Tests/PullRequestInBuildAgentTest.cs#L26 and https://github.com/GitTools/GitVersion/tree/1f8ff17dbab759b20ee361e7a6fc0488c985a803/src/GitVersionCore.Tests/BuildAgents

2021-01-15 22:32 UTC, matkoch commented
There is no pull-request support yet. Honestly, other tests look more like repeating the implementation (or testing `BuildAgentBase`). Are you sure you don't want to have a sample CI instead?

2021-01-18 12:36 UTC, asbjornu commented
Yes, the latest builds can be downloaded from [the GitHub Package registry](https://github.com/orgs/GitTools/packages?repo_name=GitVersion).

2021-01-18 12:39 UTC, asbjornu commented
@matkoch, the tests ensure that the build server implementation output the expected stuff. We need tests for that. A sample CI would be fine as well, but does not alleviate the need for tests.

2021-04-30 14:54 UTC, matkoch commented
Tests added. Sorry for the long delay!

2021-04-30 22:38 UTC, asbjornu commented
Awesome, @matkoch! If you could please rebase against `HEAD` of `main`, this should be good to go! :shipit:

2021-05-03 09:13 UTC, arturcic requested changes

2021-05-03 09:13 UTC, arturcic commented on src/GitVersionCore.Tests/BuildAgents/SpaceAutomationTests.cs
> +            githubSetEnvironmentTempFilePath = Path.GetTempFileName();
I wonder why would you need the `githubSetEnvironmentTempFilePath` here in the `SpaceAutomation` tests

2021-05-03 09:13 UTC, arturcic commented on src/GitVersionCore.Tests/BuildAgents/SpaceAutomationTests.cs
> +            if (githubSetEnvironmentTempFilePath != null && File.Exists(githubSetEnvironmentTempFilePath))
I wonder why would you need the `githubSetEnvironmentTempFilePath` here in the `SpaceAutomation` tests

2021-05-03 12:52 UTC, matkoch commented
Updated

2021-05-03 12:56 UTC, arturcic requested changes

2021-05-03 12:56 UTC, arturcic commented on src/GitVersion.Core.Tests/BuildAgents/SpaceAutomationTests.cs
> +            }
I think this one is not needed here at all, as only the GH actions build agent is using a file, so it is needed only in the GH tests

2021-05-03 12:56 UTC, arturcic commented on src/GitVersion.Core.Tests/BuildAgents/SpaceAutomationTests.cs
> +            setEnvironmentTempFilePath = Path.GetTempFileName();
I think this one is not needed here at all, as only the GH actions build agent is using a file, so it is needed only in the GH tests

2021-05-03 12:56 UTC, arturcic commented on src/GitVersion.Core.Tests/BuildAgents/SpaceAutomationTests.cs
> +        private string setEnvironmentTempFilePath;
I think this one is not needed here at all, as only the GH actions build agent is using a file, so it is needed only in the GH tests

2021-05-03 18:14 UTC, matkoch commented
Updated.

2021-05-04 06:40 UTC, arturcic approved these changes

2021-05-04 06:45 UTC, merged

2021-05-27 09:24 UTC, matkoch commented
Just a patch increment?:)