Refresh website
GitTools/GitVersion pull request #2599
Opened 2021-02-20 01:47 UTC by asbjornu

## Description

This PR refreshes the website to match the logo created by @LazaroOnline in #2508. It also updates the documentation so it resolves #2326.

## Related Issue

Builds on #2508. Resolves #2326. Related to #2503.

## Motivation and Context

The documentation was chaotic and outdated. This PR does not complete that work, but it improves it a whole lot.

## How Has This Been Tested?

Not well enough. Many links are still not working. Work in progress, but ready for review.

## Screenshots (if appropriate):

<img width="1247" alt="front page" src="https://user-images.githubusercontent.com/12283/108579129-d46f9a00-7325-11eb-9402-ce266f9f6c78.png">

<img width="1001" alt="usage" src="https://user-images.githubusercontent.com/12283/108579142-e18c8900-7325-11eb-81f0-50785184f17b.png">

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-02-21 02:07 UTC, asbjornu commented
I'm having some [Cake problems](https://github.com/GitTools/GitVersion/pull/2599/checks?check_run_id=1944253116#step:4:110):

```
Cake Setup
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 103
   at Cake.Common.Tools.GitVersion.GitVersionRunner.Run(GitVersionSettings settings) in C:\projects\cake\src\Cake.Common\Tools\GitVersion\GitVersionRunner.cs:line 59
   at Cake.Common.Tools.GitVersion.GitVersionAliases.GitVersion(ICakeContext context, GitVersionSettings settings) in C:\projects\cake\src\Cake.Common\Tools\GitVersion\GitVersionAliases.cs:line 121
   at Submission#0.GitVersion(GitVersionSettings settings)
   at Submission#0.GetVersion(BuildParameters parameters)
   at Submission#0.<>c__DisplayClass0_6.<<Initialize>>b__114()
	Message:	GitVersion: Process returned an error (exit code 1).
	Data:	[  ]
	InnerException:	
	HelpLink:	
	Source:	Cake.Core
	HResult:	-2146233088
```

And:

```
Teardown error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Cake.Core.CakeDataService.Get[TData]() in C:\projects\cake\src\Cake.Core\CakeDataService.cs:line 36
   at Cake.Core.CakeEngineActions.<>c__DisplayClass21_0`1.<RegisterTeardown>b__0(ITeardownContext context) in C:\projects\cake\src\Cake.Core\CakeEngineActions.cs:line 64
   at Cake.Core.DefaultExecutionStrategy.PerformTeardown(Action`1 action, ITeardownContext teardownContext) in C:\projects\cake\src\Cake.Core\DefaultExecutionStrategy.cs:line 57
   at Cake.Core.CakeEngine.PerformTeardown(IExecutionStrategy strategy, ICakeContext context, Stopwatch stopWatch, CakeReport report, Boolean exceptionWasThrown, Exception thrownException) in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 436
```

Ideas, @gep13, @arturcic?

2021-02-21 08:14 UTC, gep13 commented
@asbjornu what command are you running when you get this error?

2021-02-21 08:19 UTC, arturcic commented
@gep13 `./build.ps1 -Target Build-Documentation`

2021-02-21 08:23 UTC, gep13 commented
Ah gotcha, you mean this error is coming up when running the new docs workflow? On phone, so hard to view that.

Could it be due to not everything being checked up? In the build.hmm there is an additional checkout step, which is likely required to fully assert version number.

Arguably this isn't needed for a docs build, so could be that we make that part of the Setup task conditional?

2021-02-22 10:21 UTC, asbjornu commented
> Arguably this isn't needed for a docs build, so could be that we make that part of the Setup task conditional?

Good point, @gep13. If I only knew where `Task("Setup")` was defined… 😅

2021-02-22 10:23 UTC, gep13 commented
@asbjornu this isn't a Task, but rather a setup method:

https://github.com/gittools/gitversion/blob/main/build.cake#L55

2021-02-22 10:24 UTC, asbjornu commented
Gotcha @gep13. Thanks!

2021-02-22 17:06 UTC, arturcic requested changes

2021-02-22 17:06 UTC, arturcic commented on docs/input/docs/usage/cli/arguments.md
> +    /projargs       Additional arguments to pass to msbuild
These were already removed from the code

2021-02-22 17:11 UTC, arturcic commented
@asbjornu look really great the new UI, really fresh. I had a quick review, there is one comment I added but overall looks good. I think we can merge it as it is now, later we can/need to improve with follow up PRs

2021-02-22 17:27 UTC, arturcic approved these changes

2021-02-22 17:59 UTC, merged