Fix TaggedCommitVersionStrategy performance problems
GitTools/GitVersion pull request #2800
Opened 2021-08-07 13:35 UTC by ron-macneil-youi

The problem was a branch commits x version tags nested loop that quickly
grew into the millions of iterations as the number of commits and/or
tags in a repo increased, even modestly.

Each iteration performed Git tag-to-commit resolution and GitVersion
commit object-to-object comparison, both of which take a little bit of
time and aren't particularly slow in isolation but which add up fast
when performed millions of times.

This is solved by doing a single pass over the tags, resolving each to a
commit only once; then using that to build a commit-to-tag lookup
(hashtable) keyed by commit SHA, eliminating the object comparisons; and
finally doing a single pass over the branch commits, looking up
associated tags from the hashtable by SHA, eliminating the nested loop.

Testing on a repo with ~20,000 commits and ~5,000 tags showed an overall
GitVersion run time reduction from over 2 minutes down to around 5
seconds.

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-08-09 21:31 UTC, asbjornu requested changes
This looks great!

2021-08-09 21:31 UTC, asbjornu commented on src/GitVersion.Core/VersionCalculation/BaseVersionCalculators/TaggedCommitVersionStrategy.cs
> +            if (currentBranch is null) return Enumerable.Empty<BaseVersion>();
```suggestion
            if (currentBranch is null) 
                return Enumerable.Empty<BaseVersion>();
```

2021-08-09 23:23 UTC, asbjornu commented
Can you please run `dotnet format ./ --folder --exclude **/AddFormats/`, commit the changes and push?

2021-08-10 03:18 UTC, ron-macneil-youi commented
Hi @asbjornu I ran the `dotnet format` command and it hasn't changed anything.  Were you expecting a particular change?

2021-08-10 22:00 UTC, asbjornu approved these changes

2021-08-10 22:01 UTC, merged

2021-08-18 14:25 UTC, arturcic commented
<!-- GitReleaseManager release comment -->
:tada: This issue has been resolved in version 5.7.0 :tada:
The release is available on:
- [GitHub Release](https://github.com/GitTools/GitVersion/releases/tag/5.7.0)
- [Chocolatey Package](https://chocolatey.org/packages/GitVersion.Portable/5.7.0)
- [.Net Global Tool](https://www.nuget.org/packages/GitVersion.Tool/5.7.0)

Your **[GitReleaseManager](https://github.com/GitTools/GitReleaseManager)** bot :package::rocket: