docs: Guidance on git tagging
GitTools/GitVersion pull request #3741
Opened 2023-10-28 18:52 UTC by SRNissen

## Description

1. Documentation updated to address the idiosyncrasies of git tagging
2. A tiny bit of style maintenance on the affected document (It starts out as 80 columns, then halfway through changes to "whatever works, works" so now it's 80 columns throughout, excepting links/code that might be broken from such treatment. The text, when rendered, remain the same.

## Related Issue

This closes https://github.com/GitTools/GitVersion/issues/3740

## Motivation and Context

For several hours, the pre-PR documentation left me confused about how gitversion was broken.

## How Has This Been Tested?

Documentation-only change

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Doc change only, other points do not apply.

2023-10-28 19:06 UTC, SRNissen commented
I can confirm, independently of the testing workflow, that the link causing the build failure does not work.

It is a link in a different part of the documentation, located at:

https://gitversion.net/docs/learn/branching-strategies/githubflow/

that has nothing to do with this change.

Still, it might be better to do something about the issue. Are there any policies on removing links?

2023-11-06 09:11 UTC, asbjornu requested changes

2023-11-06 09:11 UTC, asbjornu commented on docs/input/docs/reference/version-increments.md
> +at [git-scm.com][git-tagging].
```suggestion
their own command. For more information, read the [git documentation on
tagging][git-tagging].
```

2023-11-06 09:11 UTC, asbjornu approved these changes

2023-11-06 09:31 UTC, arturcic commented
@asbjornu the `Verify & Publish Docs` seem to be fine so I think you can merge it, in case you're fine with the PR. The other required workflows won't run as there is no change in the src folder

2023-11-06 09:38 UTC, merged