[Feature] Same version computed on different branches #3453
GitTools/GitVersion pull request #3898
Opened 2024-02-06 10:34 UTC by HHobeck

[Feature] Same version computed on different branches:
- #3453

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-02-06 10:36 UTC, HHobeck commented
Hi @asbjornu. I'm not sure if you are agree with the new branch related property with name `take-incremented-version`. Please take a look and give me feedback.

Thank's

2024-02-07 11:00 UTC, asbjornu requested changes

2024-02-07 11:00 UTC, asbjornu commented on docs/input/docs/reference/configuration.md
> +    take-incremented-version: TakeAlwaysIncrementedVersion
Hm, I think `take-incremented-version: TakeAlwaysIncrementedVersion` have room for improvements. Give me some time to think through the use case and see if I can come up with better names.

2024-02-08 21:21 UTC, asbjornu commented
Do I understand this issue correctly when it's about whether we want to consider the `git tag` of the current commit or not? If so, perhaps `ignore-tag: False` would be more intuitive?

2024-02-09 07:08 UTC, HHobeck commented
> Do I understand this issue correctly when it's about whether we want to consider the `git tag` of the current commit or not? If so, perhaps `ignore-tag: False` would be more intuitive?

At the end the criteria you are mentioned is correct. But you need to think about the semantic meaning. We have one or more strategies who are determining the existing base versions with a indication should the base increment yes or no. We are calculating based on this the next version and take the one which is highest. The result is we have exactly one base version and one incremented version (which might be equal). Now this feature comes in place where we want for some branches not to use the incremented version but the base version. 

I can think of the following use cases:
- Take always the base version and not the incremented version,
- Take the base version when the current commit was released otherwise the incremented version,
- Take always the incremented version and not the base version

Your proposed property with name `ignore-tag` does not reflect this semantic meaning if you ask me. It's also not about ignoring tags because the current tag will be considered and used to calculate the incremented version. If someone uses the `ignore-tag` property he could expect that all tags are ignored on the branch and not considered for the version calculation (like you would specify to ignore commits).

Does it make sense?

2024-02-09 07:25 UTC, HHobeck commented
> I can think of the following use cases:
> 
> - Take always the base version and not the incremented version,
> - Take the base version when the current commit was released otherwise the incremented version,
> - Take always the incremented version and not the base version

While writing this I came up with the problem that we needs to extend the criteria e.g. for trunk based workflows. Because on trunk based workflows the released version on main will be not always marked with a tag (it's optional). So the criteria might:

- The current commit was tagged or the current branch IsMain (at least when trunk-based stratregy was used)

2024-02-09 12:01 UTC, asbjornu commented
Right. But wouldn't then `increment: None` work, since for the specific branch we don't want to increment either `Major`, `Minor` or `Patch`?

2024-02-09 14:12 UTC, HHobeck commented
> Right. But wouldn't then `increment: None` work, since for the specific branch we don't want to increment either `Major`, `Minor` or `Patch`?

But we want to increment the version on the branch but only if the commit was not released (marked with a tag).

2024-02-11 13:20 UTC, HHobeck commented
Maybe the following enum values are better:

```csharp
internal enum TakeIncrementedVersion
{
    Never,
    IfNotReleased/Tagged,
    Always
}
```

2024-02-14 22:03 UTC, asbjornu commented on docs/input/docs/reference/configuration.md
> +    take-incremented-version: TakeAlwaysIncrementedVersion
Let's do as discussed on Slack and group this and `prevent-increment-of-merged-branch-version` into a new top-level property as such:

```yaml
prevent-increment:
    when-versioned-branch-merged: true
    when-tagged: true
```

2024-02-16 06:25 UTC, HHobeck commented
> ```yaml
> prevent-increment:
>     when-versioned-branch-merged: true
>     when-tagged: true
> ```

Actually I would like to do this in a separate PR if you not mind. Please review the changes and merge it to main. Thank you.

2024-02-22 08:21 UTC, HHobeck commented
I think this PR can be merged right!?

2024-02-22 15:26 UTC, asbjornu commented on src/GitVersion.Core.Tests/IntegrationTests/DevelopScenarios.cs
> +        fixture.AssertFullSemver("1.1.0-alpha.0");
Indeed! :)

2024-02-22 22:42 UTC, asbjornu approved these changes

2024-02-22 22:42 UTC, merged