[Documentation]: Documenting the GitFlow workflow and create sequence diagrams
GitTools/GitVersion pull request #4064
Opened 2024-06-10 12:38 UTC by HHobeck

## Description
- #4063

Close #4063

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-06-24 08:11 UTC, arturcic commented
@asbjornu can you review the PR? thanks

2024-06-25 16:40 UTC, HHobeck commented
@arturcic please merge this. Only the documentation has changed

2024-06-25 16:52 UTC, arturcic requested changes

2024-06-25 16:52 UTC, arturcic commented on docs/input/docs/learn/branching-strategies/gitflow/examples.md
> +Sometimes you
I think we can remove the newline here

2024-06-25 16:54 UTC, arturcic commented on docs/input/docs/learn/branching-strategies/gitflow/examples.md
> +to keep it off main. In these scenarios you can either create a long lived
```suggestion
Sometimes you want to start on a large feature which may take a while 
to stabilize so you want to keep it off main. 
In these scenarios you can either create a long lived
```

2024-06-25 17:53 UTC, arturcic approved these changes

2024-06-25 17:53 UTC, merged